"""added constraint on delete

Revision ID: 4fa2fccd6899
Revises: 520f67f5cee0
Create Date: 2025-11-16 14:30:23.904807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fa2fccd6899'
down_revision: Union[str, None] = '520f67f5cee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('threat_request_threat_id_fkey', 'threat_request', type_='foreignkey')
    op.create_foreign_key(None, 'threat_request', 'threat', ['threat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_request', type_='foreignkey')
    op.create_foreign_key('threat_request_threat_id_fkey', 'threat_request', 'threat', ['threat_id'], ['id'])
    # ### end Alembic commands ###
