"""added ThreatRequest model

Revision ID: 520f67f5cee0
Revises: 310b1b9e148f
Create Date: 2025-11-16 13:00:27.817367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '520f67f5cee0'
down_revision: Union[str, None] = '310b1b9e148f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'DELETE', name='requestaction'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='requeststatus'), nullable=False),
    sa.Column('threat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threat_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_request_action'), 'threat_request', ['action'], unique=False)
    op.create_index(op.f('ix_threat_request_requested_by'), 'threat_request', ['requested_by'], unique=False)
    op.create_index(op.f('ix_threat_request_status'), 'threat_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_request_status'), table_name='threat_request')
    op.drop_index(op.f('ix_threat_request_requested_by'), table_name='threat_request')
    op.drop_index(op.f('ix_threat_request_action'), table_name='threat_request')
    op.drop_table('threat_request')
    # ### end Alembic commands ###
