"""Added threats table

Revision ID: 62512fee7f54
Revises: 0c00169d2196
Create Date: 2025-11-09 14:13:00.191779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62512fee7f54'
down_revision: Union[str, None] = '0c00169d2196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('route_user_id_fkey', 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key('route_user_id_fkey', 'route', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
