"""Added table EndpointMetrics

Revision ID: 7a441878d217
Revises: a484536cadae
Create Date: 2025-11-04 19:12:59.170961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a441878d217'
down_revision: Union[str, None] = 'a484536cadae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('min_response_time_ms', sa.Float(), nullable=False),
    sa.Column('max_response_time_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('success_rate_percent', sa.Float(), nullable=False),
    sa.Column('first_request_at', sa.DateTime(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_metrics_endpoint'), 'endpoint_metrics', ['endpoint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_metrics_endpoint'), table_name='endpoint_metrics')
    op.drop_table('endpoint_metrics')
    # ### end Alembic commands ###
