"""Added routes model

Revision ID: 7e325cb519ae
Revises: 62256f1fabe7
Create Date: 2025-10-05 14:14:50.486004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e325cb519ae'
down_revision: Union[str, None] = '62256f1fabe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('route_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_route_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_point', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('end_point', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intermediate_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_algorithm'), 'route', ['algorithm'], unique=False)
    op.create_index(op.f('ix_route_created_at'), 'route', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_name'), 'route', ['name'], unique=False)
    op.create_index(op.f('ix_route_user_id'), 'route', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_user_id'), table_name='route')
    op.drop_index(op.f('ix_route_name'), table_name='route')
    op.drop_index(op.f('ix_route_created_at'), table_name='route')
    op.drop_index(op.f('ix_route_algorithm'), table_name='route')
    op.drop_table('route')
    # ### end Alembic commands ###
