"""Made name field nullable

Revision ID: 882079be5ab6
Revises: e237d4ec4144
Create Date: 2025-01-24 14:05:15.951811

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "882079be5ab6"
down_revision: Union[str, None] = "e237d4ec4144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
