"""Added last_request_time_ms

Revision ID: 9479b8dc7650
Revises: a6a4738e38c1
Create Date: 2025-11-04 19:58:47.055165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9479b8dc7650'
down_revision: Union[str, None] = 'a6a4738e38c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_metrics', sa.Column('last_request_time_ms', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_metrics', 'last_request_time_ms')
    # ### end Alembic commands ###
