"""Added point names to the route model

Revision ID: 97f9623065d3
Revises: c5692ab42f55
Create Date: 2025-10-19 16:08:52.002047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97f9623065d3'
down_revision: Union[str, None] = 'c5692ab42f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('start_point_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('end_point_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('route', sa.Column('intermediate_point_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_route_end_point_name'), 'route', ['end_point_name'], unique=False)
    op.create_index(op.f('ix_route_start_point_name'), 'route', ['start_point_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_start_point_name'), table_name='route')
    op.drop_index(op.f('ix_route_end_point_name'), table_name='route')
    op.drop_column('route', 'intermediate_point_names')
    op.drop_column('route', 'end_point_name')
    op.drop_column('route', 'start_point_name')
    # ### end Alembic commands ###
