"""Added RequestMetrics model

Revision ID: a484536cadae
Revises: 97f9623065d3
Create Date: 2025-10-26 16:08:06.236994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a484536cadae'
down_revision: Union[str, None] = '97f9623065d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metrics_endpoint'), 'request_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_request_metrics_timestamp'), 'request_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_metrics_timestamp'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_endpoint'), table_name='request_metrics')
    op.drop_table('request_metrics')
    # ### end Alembic commands ###
