"""Added algorithm field

Revision ID: a6a4738e38c1
Revises: 7a441878d217
Create Date: 2025-11-04 19:43:50.304217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6a4738e38c1'
down_revision: Union[str, None] = '7a441878d217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_metrics', sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_endpoint_metrics_endpoint', table_name='endpoint_metrics')
    op.create_index(op.f('ix_endpoint_metrics_endpoint'), 'endpoint_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_endpoint_metrics_algorithm'), 'endpoint_metrics', ['algorithm'], unique=False)
    op.create_unique_constraint('uix_endpoint_algorithm', 'endpoint_metrics', ['endpoint', 'algorithm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_endpoint_algorithm', 'endpoint_metrics', type_='unique')
    op.drop_index(op.f('ix_endpoint_metrics_algorithm'), table_name='endpoint_metrics')
    op.drop_index(op.f('ix_endpoint_metrics_endpoint'), table_name='endpoint_metrics')
    op.create_index('ix_endpoint_metrics_endpoint', 'endpoint_metrics', ['endpoint'], unique=True)
    op.drop_column('endpoint_metrics', 'algorithm')
    # ### end Alembic commands ###
