"""Updated location field in threat related tables

Revision ID: ba68ce64922a
Revises: 4fa2fccd6899
Create Date: 2025-11-22 14:33:49.656489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba68ce64922a'
down_revision: Union[str, None] = '4fa2fccd6899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
