"""Added threats to the route schema

Revision ID: c5692ab42f55
Revises: 7e325cb519ae
Create Date: 2025-10-19 15:11:54.916547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5692ab42f55'
down_revision: Union[str, None] = '7e325cb519ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('threats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'threats')
    # ### end Alembic commands ###
